#!/usr/bin/env python

from datetime import datetime
import os
import re
import sys

args       = sys.argv[1:]
is_today   = [x for x in args if x == "--t"]
if "--t" in args:
    args.remove("--t")

target_dir = [x for x in args if os.path.exists(x)]

pattern  = ".+".join([x.replace(".", "\.") for x in args if not os.path.exists(x)])
dir_path = os.getcwd() if len(target_dir) == 0 else target_dir[0]

print("matches: {}".format(pattern))
print
print("|last modified time  | file")

def get_last_modified_time(abs_path):
    return datetime.fromtimestamp(
               os.path.getmtime(
                   abs_path
               )
           )

def get_last_modified_time_str(lmt):
    return str(lmt)[0:-7]

def matches_date(is_today, lmt):
    if not is_today:
        return true

    return (
               lmt.year  == datetime.today().year  and \
               lmt.month == datetime.today().month and \
               lmt.day   == datetime.today().day
           )

for path, subdirs, files in os.walk(dir_path):
    for name in files:
        abs_path = os.path.join(path, name)
        if re.search(pattern, abs_path):
            lmt = get_last_modified_time(abs_path)
            if (not is_today) or (matches_date(is_today, lmt)):
                print "|{} | {}".format(
                          get_last_modified_time_str(lmt),
                          abs_path
                      )

print
